name: tmanager
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  go_router: ^14.7.1
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  logger: ^2.5.0

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.4.0
  uuid: ^4.5.1

dev_dependencies:
  analyzer:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
