name: tmanager
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  go_router: ^14.7.1

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.4.0

dev_dependencies:
  analyzer:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
